[build]
  # 构建命令（根据你的项目实际情况，Vue 项目通常是 npm run build）
  command = "npm run build" 
  # 构建输出目录（Vue 项目默认是 dist）
  publish = "dist"  

# 第一个重定向规则：单页应用路由（保留原有规则）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 第二个重定向规则：Seatable API 代理（新增规则）
[[redirects]]
  from = "/seatable-api/*"  # 匹配前端请求的路径
  to = "https://cloud.seatable.cn/:splat"  # 转发到实际API（替换为真实地址）
  status = 200  # 必须为200（透明代理）
  force = true  # 强制覆盖默认行为
  headers = {
    "Access-Control-Allow-Origin" = "*",  # 允许跨域
    "Access-Control-Allow-Methods" = "GET, POST, PUT, DELETE"
  }